apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-idler
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-idler
  template:
    metadata:
      labels:
        app: faas-idler
    spec:
      containers:
      - name: faas-idler
        image: quay.io/openfaas/faas-idler:0.4.0
        env:
        - name: gateway_url
          value: "http://gateway:8080"
        - name: prometheus_host
          value : "http://prometheus:9000"
        - name: inactivity_duration
          value: "30s"
        - name: reconcile_interval
          value: "30s"
        - name: max_scale_down
          value: "10"
        - name: dry_run
          value: "false"
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-idler
  namespace: openfaas
