networks:
  public:
    external: true
secrets:
    basic-auth-user:
        external: true
    basic-auth-password:
        external: true
services:
  pcap-api:
    deploy:
      labels:
        traefik.enable: "false"
        traefik.http.routers.pcap-api.entrypoints: websecure
        traefik.http.routers.pcap-api.service: pcap-api
        traefik.http.routers.pcap-api.tls.certresolver: leresolver
        traefik.http.services.pcap-api.loadbalancer.server.port: '8000'
      mode: replicated
      replicas: 1
    environment:
      PROF_GROUP: enseignants_permissions
      DATABASE_HOST: pcap-db
      DATABASE_NAME: postgres
      OPENFAAS_URL: http://gateway:8080
      OPENFAAS_USERNAME_FILE: /run/secrets/basic-auth-user
      OPENFAAS_PASSWORD_FILE: /run/secrets/basic-auth-password
    secrets:
    - source: basic-auth-user
    - source: basic-auth-password
    image: jrobert2/pcap-api:1.03
    entrypoint: /bin/sh
    command: |-
      -c '
      apt-get update --allow-releaseinfo-change &&
      apt-get update &&
      echo "pews.univ-orleans.fr" > /etc/mailname &&
      DEBIAN_FRONTEND=noninteractive apt-get install postfix -y &&
      postconf -e "myhostname = localhost" &&
      postconf -e "mydestination = localhost.univ-orleans.fr, localhost" &&
      postconf -e "relayhost = smtp.univ-orleans.fr" &&
      service postfix restart &&
      python3 manage.py migrate || exit 0 &&
      pip3 install --no-input -e git+https://gitlab.com/FlorentBecker2/docker-exerciseur.git#egg=docker_exerciseur &&
      python3 manage.py runserver 0.0.0.0:8000
      '
    networks:
      public: {}
    volumes:
    - pcap-api:/pcap-api:rw # Serveur NFS pour cluster Multi Noeuds
    # - /home/lifoadm/pcap-deployment-master/Stacks/src/pcap-api:/pcap-api:rw # Pour cluster Mono - Noeuds sur pcap-master
    - /var/run/docker.sock:/var/run/docker.sock:rw
  pcap-celery-worker:
    command: |-
      -c '
      apt-get update --allow-releaseinfo-change &&
      apt-get update &&
      echo "pews.univ-orleans.fr" > /etc/mailname &&
      DEBIAN_FRONTEND=noninteractive apt-get install postfix -y &&
      postconf -e "myhostname = localhost" &&
      postconf -e "mydestination = localhost.univ-orleans.fr, localhost" &&
      postconf -e "relayhost = smtp.univ-orleans.fr" &&
      service postfix restart &&
      exec celery -A pcap_api worker
      '
    deploy:
      mode: replicated
      replicas: 1
    entrypoint: /bin/sh
    environment:
      PROF_GROUP: enseignants_permissions
      DATABASE_HOST: pcap-db
      DATABASE_NAME: postgres
      OPENFAAS_URL: http://gateway:8080
      OPENFAAS_USERNAME_FILE: /run/secrets/basic-auth-user
      OPENFAAS_PASSWORD_FILE: /run/secrets/basic-auth-password
    secrets:
    - source: basic-auth-user
    - source: basic-auth-password
    image: jrobert2/pcap-api:1.03
    networks:
      public: {}
    volumes:
    - pcap-api:/pcap-api:rw # Serveur NFS pour cluster Multi Noeuds
    # - /home/lifoadm/pcap-deployment-master/Stacks/src/pcap-api:/pcap-api:rw # Pour cluster Mono - Noeuds sur pcap-master 
    - /var/run/docker.sock:/var/run/docker.sock:rw
  pcap-convergence:
    deploy:
      mode: replicated
      replicas: 1
    image: convergencelabs/convergence-omnibus:1.0.0-rc.6
    networks:
      public: {}
    restart: always
  pcap-db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:16.1
    networks:
      public: {}
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
  pcap-nginx:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.nginx.entrypoints: websecure
        traefik.http.routers.nginx.rule: Host(`<DomainName>`)
        traefik.http.routers.nginx.service: nginx
        traefik.http.routers.nginx.tls.certresolver: leresolver
        traefik.http.services.nginx.loadbalancer.server.port: '80'
      mode: replicated
      replicas: 1
    image: jrobert2/pcap-nginx:convergence
    networks:
      public: {}
    restart: always
    volumes:
    - readthedocs.org:/readthedocs:rw
    - /mnt/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
  pcap-rabbitmq:
    image: rabbitmq:latest
    networks:
      public: {}
    restart: always
  pcap-registry:
    deploy:
      mode: replicated
      replicas: 1
    image: registry:2
    networks:
      public: {}
    ports:
    - 127.0.0.1:5000:5000/tcp
    volumes:
    - nfs_docker_registry:/var/lib/registry:rw
  pcap-rtd:
    deploy:
      labels:
        traefik.enable: "false"
        traefik.http.routers.rtd.entrypoints: websecure
        traefik.http.routers.rtd.service: rtd
        traefik.http.routers.rtd.tls.certresolver: leresolver
        traefik.http.services.rtd.loadbalancer.server.port: '8000'
      mode: replicated
      replicas: 1
    environment:
      PROF_GROUP: enseignants
      EasyPythonProduction: "true"
      PCAP_API_SERVER: pcap-api-rest:8000/pcap
      PCAP_API_URI: http://localhost/pcap/api/v1/
      RTD_PRODUCTION_DOMAIN: <DomainName>:80
      no_proxy: '"localhost,127.0.0.1,pcap-api-rest,pcap-rtd-db"'
    image: jrobert2/rtd:1.0
    networks:
      public: {}
    volumes:
    - readthedocs.org:/readthedocs.org:rw
version: '3.3'
volumes:
  nfs_docker_registry: {}
  postgres-data: {}
  readthedocs.org: {}
  pcap-api: {}
