global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'faas'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'faas-idler'
    static_configs:
      - targets: ['faas-idler:8080']
